import { Resource } from './Resource'
import axiosClient from '~/lib/axios'

/**
 * Represents a Post object from the API, typically associated with a user.
 */
export interface Post {
  userId: number
  id: number
  title: string
  body: string
}

/**
 * Represents a User object from the API.
 */
export interface User {
  id: number
  name: string
  username: string
  email: string
  address: {
    street: string
    suite: string
    city: string
    zipcode: string
    geo: {
      lat: string
      lng: string
    }
  }
  phone: string
  website: string
  company: {
    name: string
    catchPhrase: string
    bs: string
  }
}

/**
 * Data type for creating a new user. It omits the 'id' field,
 * which is typically generated by the server.
 */
export type UserCreate = Omit<User, 'id'>

/**
 * Data type for updating an existing user. All fields are optional.
 */
export type UserUpdate = Partial<UserCreate>

/**
 * Extends the generic Resource to create a specific API client for Users.
 * It inherits all standard CRUD methods and can have its own user-specific methods.
 */
class UserApi extends Resource<User, UserCreate, UserUpdate> {
  constructor() {
    // The URI for the user resource is 'users'.
    super('users')
  }

  /**
   * Fetches all posts for a specific user.
   * This is an example of a custom method that doesn't fit the standard CRUD pattern.
   * @param {number} userId - The ID of the user whose posts are to be fetched.
   * @returns {Promise<Post[]>} A promise that resolves to an array of posts.
   */
  public getPosts(userId: number): Promise<Post[]> {
    // This makes a GET request to the endpoint `/users/{userId}/posts`
    return axiosClient.get(`/${this.uri}/${userId}/posts`)
  }
}

/**
 * An API client instance for the 'users' resource.
 * It uses the extended UserApi class to provide both CRUD operations and custom functions.
 */
const userApi = new UserApi()

export default userApi

/*
 * EXAMPLE USAGE in your components or hooks:
 *
 * import userApi from '~/api/User';
 *
 * // Using an inherited method from Resource
 * const fetchUsers = async () => {
 *   const users = await userApi.list();
 *   // ... do something with the list of users
 * }
 *
 * // Using a custom method from UserApi
 * const fetchUserPosts = async (userId: number) => {
 *   const posts = await userApi.getPosts(userId);
 *   // ... do something with the user's posts
 * }
 */
